/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStudyGroupsRouteImport } from './routes/app.study-groups'
import { Route as AppSocialRouteImport } from './routes/app.social'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppLearnRouteImport } from './routes/app.learn'
import { Route as AppLeaderboardsRouteImport } from './routes/app.leaderboards'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAiTutorRouteImport } from './routes/app.ai-tutor'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyGroupsRoute = AppStudyGroupsRouteImport.update({
  id: '/study-groups',
  path: '/study-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAiTutorRoute = AppAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/learn': typeof AppLearnRoute
  '/app/notes': typeof AppNotesRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/study-groups': typeof AppStudyGroupsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/api/chat': typeof ApiChatRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/learn': typeof AppLearnRoute
  '/app/notes': typeof AppNotesRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/study-groups': typeof AppStudyGroupsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/ai-tutor': typeof AppAiTutorRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/learn': typeof AppLearnRoute
  '/app/notes': typeof AppNotesRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/social': typeof AppSocialRoute
  '/app/study-groups': typeof AppStudyGroupsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/api/chat'
    | '/app/ai-tutor'
    | '/app/calendar'
    | '/app/flashcards'
    | '/app/leaderboards'
    | '/app/learn'
    | '/app/notes'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/resources'
    | '/app/settings'
    | '/app/social'
    | '/app/study-groups'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/chat'
    | '/app/ai-tutor'
    | '/app/calendar'
    | '/app/flashcards'
    | '/app/leaderboards'
    | '/app/learn'
    | '/app/notes'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/resources'
    | '/app/settings'
    | '/app/social'
    | '/app/study-groups'
    | '/app'
  id:
    | '__root__'
    | '/app'
    | '/api/chat'
    | '/app/ai-tutor'
    | '/app/calendar'
    | '/app/flashcards'
    | '/app/leaderboards'
    | '/app/learn'
    | '/app/notes'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/resources'
    | '/app/settings'
    | '/app/social'
    | '/app/study-groups'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-groups': {
      id: '/app/study-groups'
      path: '/study-groups'
      fullPath: '/app/study-groups'
      preLoaderRoute: typeof AppStudyGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/social': {
      id: '/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboards': {
      id: '/app/leaderboards'
      path: '/leaderboards'
      fullPath: '/app/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-tutor': {
      id: '/app/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/app/ai-tutor'
      preLoaderRoute: typeof AppAiTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiTutorRoute: typeof AppAiTutorRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppLearnRoute: typeof AppLearnRoute
  AppNotesRoute: typeof AppNotesRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppStudyGroupsRoute: typeof AppStudyGroupsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiTutorRoute: AppAiTutorRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppLearnRoute: AppLearnRoute,
  AppNotesRoute: AppNotesRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppStudyGroupsRoute: AppStudyGroupsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
